version: "3"
services:
  api:
    build: api
    volumes:
      - api-log:/logs
    depends_on:
      - mongo
      - proxy
    networks:
      - frontend
      - backend

  web:
    build: web
    depends_on:
      - api
      - proxy
    networks:
      - frontend

  proxy:
    build: proxy
    networks:
      - frontend
    ports:
      - "80:80"
  
  mongo:
    image: mongo
    networks:
      - backend

volumes:
  api-log:

networks:
  frontend:
  backend: