version: "3"
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - api-log:/logs
    links:
      - mongo
    depends_on:
      - mongo
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - api
  mongo:
    image: mongo
    ports:
      - "27017:27017"

volumes:
  api-log: